// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xwnurrslkbxvnjihclkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bnVycnNsa2J4dm5qaWhjbGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0NTAxMzYsImV4cCI6MjA5MjAyNjEzNn0.ACaJXPAbdskc8V4JDGbP5xmGTZobLagxg7meNEsgUUE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);